### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by adamnimmo** [nwithan8/PlexRecs#1]
I am coming across an issue when launching the script

```
  File "PlexRecs.py", line 175
    \'new\' and \'%<your Plex username>\'.")
    ^
IndentationError: expected an indented block
```

Can you advise if I should be changing something on this line.

**Comment by nwithan8** [comment]
No, nothing needs to be changed. Make sure that entire line is just one line and that it didn't get split. Depending on how you copied and pasted and the size of your terminal window, it might have shifted it down into two lines.

**Comment by adamnimmo** [comment]
Thanks mate, that was it. Working out some other bugs with the SSL cert to Discord now.
