### ISSUE TITLE
can't get Trakt auth code

### ISSUE THREAD

**Issue by demha89** [nwithan8/PlexRecs#10]
I keep getting this error: 
OAUTH ERROR
The requested redirect uri is malformed or doesn't match client redirect URI

is there a way to setup Trakt properly? coz I really hate it

**Comment by nwithan8** [comment]
What redirect URI did you use for your Trakt application?

**Comment by demha89** [comment]
I used trakt API link. Didn't know what to put there

**Comment by nwithan8** [comment]
Use urn:ietf:wg:oauth:2.0:oob

**Comment by demha89** [comment]
worked! thanks so much
