### ISSUE TITLE
Can't Install Modules

### ISSUE THREAD

**Issue by KevinFumbles** [nwithan8/PlexRecs#2]
I tried running PlexRecsGeneral.py after editing it, and it's giving me an invalid syntax error for the ```pip install``` line. I tried installing it outside of the script but when I run it after (and comment out the ```pip install``` line), it can't find the modules. I also tried doing an ```os.system``` call for that line since I tried looking it up and apparently pip can only be run from the command line, not a python interpreter. Though it gave me the same result as installing it outside of the script. Am I misinterpreting the install instructions or something else?

**Comment by nwithan8** [comment]
Try installing those modules again (outside the script), but use pip3 instead of pip.

I need to make a requirements.txt file for pip/pip3 in the future, rather than having a commented line in the script.

**Comment by KevinFumbles** [comment]
pip3 worked! As a side note, I'm testing it out with 3.7 and it seems to be working fine. I have been running into issues with the different versions of discord coding though (rewrite vs async). Kind of an amateur with python and straight up noob with discord but I have edited it and will post a change if you want to check it out and possibly update the git.

**Comment by nwithan8** [comment]
Thanks. Yeah, I released the code just around the time they did a major rewrite for discord.py. Haven't had much of an opportunity to mess around with the rewrite and update my bot. If you've forked it and updated it, let me know and I'll merge it.

**Comment by KevinFumbles** [comment]
By the way, just updated the bot so it works with 3.7 and Rewrite if you want to merge them.
