### ISSUE TITLE
Command raised an exception

### ISSUE THREAD

**Issue by FSCorrupt** [nwithan8/PlexRecs#6]
Logged in as : Plex Stats - ******************
Version: 1.3.3

Successfully logged in and booted...!

when i type in Discord: ***recommend show** (same error on all Libraries)
im getting: 

> Looking for a show...
> Sorry, something went wrong while looking for a recommendation.

in Python log i can see following:

> Command raised an exception: AttributeError: 'SmallMediaItem' object has no attribute 'type'

any hints?

**Comment by nwithan8** [comment]
Apologies, there was a bit of coding missing that got lost as I transferred features from the Arca version of PlexRecs back into this standalone. Issue has been corrected in commit 1e1def9f6ac64666ea86966e730d5142eaf1cc71

**Comment by FSCorrupt** [comment]
Thanks for the Quick Fix, its working now.
